"project_id": "YOUR_PROJECT_ID"
"api_token": "YOUR_PERSONAL_TOKEN"
"preserve_hierarchy": true
"files": [
  {
    "source": "/_locales/en_AU/messages.json",
    "translation": "/_locales/%locale%/messages.json"
  }
]